name: Tests on PR

on:
  push:
    branches:
      - main
      - cookie
  pull_request:
  workflow_dispatch:

jobs:
  validate:
    defaults:
      run:
        shell: bash -l {0}

    runs-on: ubuntu-latest
    steps:
      - name: Check out diffpy.labpdfproc repository
        uses: actions/checkout@v4

      - name: Initialize miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: test
          auto-update-conda: true
          environment-file: environment.yml
          auto-activate-base: false
          python-version: 3.11

      - name: Conda config
        run: >-
          conda config --set always_yes yes
          --set changeps1 no

      - name: Install libgtk for Linux
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev

      - name: Install diffpy.labpdfproc and requirements
        run: |
          conda install --file requirements/test.txt
          pip install -r requirements/pip.txt
          python -m pip install . --no-deps


      - name: Validate diffpy.labpdfproc
        run: |
          pytest --cov
          coverage report -m
          codecov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          verbose: true
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
